skip -gfi /usr/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*/*
skip -gfi /usr/*/*/*/*/*
skip -gfi /usr/*/*/*/*
skip -gfi /usr/*/*/*
skip -gfi /usr/*/*
skip -gfi /usr/*
skip -gfi /opt/gitache/*/*/*/*/*
skip -gfi /opt/gitache/*/*/*/*
skip -gfi /opt/gitache/*/*/*
skip -gfi /opt/gitache/*/*
skip -gfi /opt/gitache/*
skip -rfu ^utils::
skip -rfu ^tracked::
skip -rfu ^AIRefCount::
